import os
from datetime import datetime
from pathlib import Path
from typing import List, Dict
from playwright.async_api import Page

class Reporter:
    def __init__(self, base_dir: str = "test_results/elentra_crawl"):
        self.base_dir = Path(base_dir)
        self.screenshot_dir = self.base_dir / "screenshots"
        self.screenshot_dir.mkdir(parents=True, exist_ok=True)
        self.results: List[Dict] = []

    async def capture_screenshot(self, page: Page, url: str):
        # Create a safe filename from URL
        safe_name = "".join(c for c in url if c.isalnum() or c in " _-").strip()
        if not safe_name or safe_name == "httpselentraru":
             safe_name = "homepage"
        
        path = self.screenshot_dir / f"{safe_name[:50]}.png"
        await page.screenshot(path=str(path), full_page=True)
        return str(path)

    def add_result(self, url: str, status: str, errors: List[str], screenshot_path: str):
        self.results.append({
            "url": url,
            "status": status,
            "errors": errors,
            "screenshot": screenshot_path
        })

    def generate_markdown_report(self, target_file: str = "E2E_TEST_REPORT.md"):
        report_path = Path(target_file)
        
        with open(report_path, "w", encoding="utf-8") as f:
            f.write("# E2E Test Report: Elentra Nutrition\n\n")
            f.write(f"**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
            f.write(f"**Total Pages Tested:** {len(self.results)}\n\n")
            
            f.write("## Summary Table\n\n")
            f.write("| URL | Status | Errors | Screenshot |\n")
            f.write("| --- | ------ | ------ | ---------- |\n")
            
            for res in self.results:
                status_icon = "✅ PASS" if not res["errors"] else "❌ FAIL"
                error_list = "<br>".join(res["errors"]) if res["errors"] else "None"
                # Use relative path for screenshots in the markdown
                if res['screenshot']:
                    rel_screenshot = os.path.relpath(res['screenshot'], report_path.parent)
                    ss_link = f"[View]({rel_screenshot})"
                else:
                    ss_link = "N/A"
                f.write(f"| {res['url']} | {status_icon} | {error_list} | {ss_link} |\n")
            
            f.write("\n\n---\n*Report generated by Antigravity AI*")
        
        return str(report_path)
